import { Inter, Orbitron, Jost } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const orbitron = Orbitron({ subsets: ["latin"], variable: "--font-orbitron" });
const jost = Jost({ subsets: ["latin"], variable: "--font-jost" });

import { Providers } from "./providers";

import Layout from "../components/layout/layout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} font-sans ${orbitron.variable} font-sans ${jost.variable} font-sans`}
      >
        <Providers>
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  );
}
